"""
ReAct agent runner.
Reason → Act (tool calls) → Observe → Repeat until final answer.

Two tool-calling modes (setting `agent_tool_mode`):
- "native": OpenAI function-calling — the server returns structured tool_calls.
  Requires the LLM server to parse tool calls (e.g. vLLM --enable-auto-tool-choice).
- "prompt": a JSON-envelope protocol described in the system prompt; the bridge
  parses the tool call out of the model's text. Works on any chat model, used as
  a fallback when the server does not emit native tool_calls.
"""
from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field

from openai import AsyncOpenAI

from agent import confidence as conf_module
from agent.language import detect as detect_lang, instruction as lang_instruction
from agent.tools.base import Tool

logger = logging.getLogger("bridge.agent")


class LLMCallError(Exception):
    """The LLM call itself failed (connection/timeout/rate-limit exhausted).

    Distinct from a low-quality-but-real model answer: this must never be
    confidence-scored or shipped to the user as content — see run().
    """


def _extract_tool_call(content: str) -> tuple[str, dict] | None:
    """Parse a prompt-mode tool-call envelope out of the model's text.

    Accepts, tolerantly (optionally wrapped in a ```json fence):
        {"tool_call": {"name": "x", "arguments": {...}}}
        {"name": "x", "arguments": {...}}
        {"tool": "x", "arguments": {...}}
    Returns (name, arguments) or None if no valid envelope is present.
    """
    if not content:
        return None
    text = content.strip()
    candidates: list[str] = []
    fence = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.S)
    if fence:
        candidates.append(fence.group(1))
    candidates.append(text)
    if "{" in text and "}" in text:
        candidates.append(text[text.find("{"): text.rfind("}") + 1])

    for cand in candidates:
        try:
            obj = json.loads(cand)
        except Exception:
            continue
        if not isinstance(obj, dict):
            continue
        tc = obj.get("tool_call")
        if isinstance(tc, dict) and tc.get("name"):
            return tc["name"], tc.get("arguments") or {}
        name = obj.get("name") or obj.get("tool")
        if name and "arguments" in obj:
            return name, obj.get("arguments") or {}
    return None

_MASTER_PROMPT_FALLBACK = (
    "You are a highly intelligent AI assistant. "
    "Help users accurately and professionally. "
    "If you need more information, ask the user. "
    "Use your available tools when appropriate."
)

# Hard language constraint — the system serves only English and Arabic.
_LANGUAGE_POLICY = (
    "--- Language Policy ---\n"
    "You must respond ONLY in English or Arabic. Never reply in any other language, "
    "regardless of the language used earlier in the conversation or inside any document, "
    "OCR text, or tool result. Match the user's language: if they write/speak Arabic, "
    "reply in Modern Standard Arabic with a professional Saudi tone; otherwise reply in English."
)

# Shown only when the LLM call itself keeps failing (connection/timeout) after
# every retry — never generated by the model, so it must stay bilingual-safe.
_LLM_UNAVAILABLE_MESSAGE = {
    "ar": "عذرًا، أواجه حاليًا صعوبة في الاتصال بخدمة الذكاء الاصطناعي. يرجى المحاولة مرة أخرى بعد قليل.",
    "en": "I'm sorry, I'm having trouble connecting to the AI service right now. Please try again in a moment.",
}

# Appended to every system prompt — the reply is delivered as a WhatsApp message.
_WHATSAPP_FORMAT_RULES = (
    "--- Output Formatting (WhatsApp) ---\n"
    "Your reply is sent as a WhatsApp message. Use WhatsApp formatting ONLY:\n"
    "- Bold: a single asterisk around text, *like this*. Never use ** or Markdown headings (#).\n"
    "- Italic: _like this_. Strikethrough: ~like this~. Monospace: ```like this```.\n"
    "- Do NOT use Markdown tables, HTML tags, or <br>. WhatsApp cannot render them.\n"
    "- For lists, put each item on its own line starting with \"• \".\n"
    "- Present structured or tabular information as short labeled lines or bullet points, never a table.\n"
    "- Keep replies concise and easy to read on a phone."
)


@dataclass
class AgentResult:
    content: str
    language: str = "en"
    tool_calls_made: list[str] = field(default_factory=list)
    confidence: float = 1.0
    iterations: int = 0


class AgentRunner:
    def __init__(
        self,
        settings: dict,
        tools: list[Tool],
    ):
        self.settings = settings
        self.tools: dict[str, Tool] = {t.name: t for t in tools}
        # The SDK retries 429/5xx with exponential backoff and honours
        # Retry-After — the DGX inference servers 429 under GPU-memory pressure.
        self.client = AsyncOpenAI(
            base_url=settings.get("ai_base_url", "http://192.168.100.62:8002/v1"),
            api_key=settings.get("ai_api_key", "none"),
            max_retries=int(settings.get("ai_max_retries", "4")),
            timeout=120.0,
        )
        self.model = settings.get("ai_model", "gpt-oss:20b")
        # "native" = OpenAI tool_calls; "prompt" = JSON-envelope parsed by the bridge.
        self.tool_mode = settings.get("agent_tool_mode", "prompt").lower()
        self.max_iterations = int(settings.get("agent_max_iterations", "10"))
        self.confidence_enabled = settings.get("confidence_enabled", "false").lower() == "true"
        self.confidence_threshold = float(settings.get("confidence_threshold", "0.7"))
        self.confidence_max_retries = int(settings.get("confidence_max_retries", "2"))
        # Separate, smaller budget for a failed LLM call (connection/timeout) —
        # distinct from confidence_max_retries, which retries a genuine but
        # low-quality answer. Kept small so a real outage surfaces to the user
        # quickly instead of making them wait through the full confidence budget.
        self.llm_connection_max_retries = int(settings.get("llm_connection_max_retries", "1"))

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    async def run(
        self,
        user_message: str,
        context_messages: list[dict],
        role_prompt: str,
        language: str,
        attachment_meta: dict | None = None,
    ) -> AgentResult:
        system_prompt = self._build_system(role_prompt, language)
        # Native mode sends the OpenAI tools schema; prompt mode describes the
        # tools (and the JSON envelope) in the system prompt instead.
        if self.tool_mode == "native":
            tools_schema = [t.to_openai_function() for t in self.tools.values()]
        else:
            tools_schema = []
            protocol = self._tool_protocol_prompt()
            if protocol:
                system_prompt = f"{system_prompt}\n\n{protocol}"

        user_content = self._build_user_content(user_message, attachment_meta)

        messages: list[dict] = (
            [{"role": "system", "content": system_prompt}]
            + context_messages
            + [{"role": "user", "content": user_content}]
        )

        tool_calls_made: list[str] = []
        final_content = ""
        final_confidence = 1.0
        final_iterations = 0
        connection_failures = 0

        # The outer loop bound must cover whichever retry budget is larger, so
        # neither the connection-retry nor the confidence-retry path gets cut
        # short by the other's setting.
        max_attempts = max(self.confidence_max_retries, self.llm_connection_max_retries) + 1

        for attempt in range(max_attempts):
            attempt_messages = list(messages)
            try:
                result_text, calls, iterations = await self._react_loop(
                    attempt_messages, tools_schema
                )
            except LLMCallError as exc:
                # The call itself failed — never confidence-score or ship this as
                # an answer. Retry with a fresh attempt (own, smaller budget), or
                # give an honest, language-appropriate apology once exhausted.
                if connection_failures < self.llm_connection_max_retries:
                    connection_failures += 1
                    logger.warning(
                        "LLM call failed (%d/%d retries) (%s) — retrying.",
                        connection_failures, self.llm_connection_max_retries, exc,
                    )
                    continue
                logger.error(
                    "LLM call failed after %d retries (%s) — giving up.",
                    connection_failures, exc,
                )
                final_content = _LLM_UNAVAILABLE_MESSAGE.get(language, _LLM_UNAVAILABLE_MESSAGE["en"])
                break

            tool_calls_made.extend(calls)
            final_iterations = iterations

            if not self.confidence_enabled:
                final_content = result_text
                break

            sc, reason = await conf_module.score(self.client, self.model, user_message, result_text)
            final_confidence = sc
            if sc >= self.confidence_threshold:
                final_content = result_text
                break

            logger.info(
                "Confidence %.2f < threshold %.2f (attempt %d/%d): %s",
                sc, self.confidence_threshold, attempt + 1, self.confidence_max_retries + 1, reason,
            )
            if attempt < self.confidence_max_retries:
                # Feed the low-confidence result back and retry
                messages.append({"role": "assistant", "content": result_text})
                messages.append({
                    "role": "user",
                    "content": (
                        f"[System note: your previous answer had low confidence "
                        f"(score {sc:.2f}): {reason}. "
                        f"Please reconsider and provide a more accurate, complete answer.]"
                    ),
                })
            else:
                final_content = result_text
                break

        return AgentResult(
            content=final_content or "I'm sorry, I couldn't generate a response.",
            language=language,
            tool_calls_made=tool_calls_made,
            confidence=final_confidence,
            iterations=final_iterations,
        )

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    async def _react_loop(
        self,
        messages: list[dict],
        tools_schema: list[dict],
    ) -> tuple[str, list[str], int]:
        """Run the Reason-Act loop. Returns (final_text, tool_names_used, iterations)."""
        tool_calls_made: list[str] = []

        for iteration in range(self.max_iterations):
            kwargs: dict = {
                "model": self.model,
                "messages": messages,
            }
            if tools_schema:
                kwargs["tools"] = tools_schema
                kwargs["tool_choice"] = "auto"

            try:
                response = await self.client.chat.completions.create(**kwargs)
            except Exception as exc:
                logger.error("LLM call failed: %s", exc)
                # Raise rather than return a fabricated "answer" — a failed call
                # must never be confidence-scored or sent to the user as content.
                raise LLMCallError(str(exc)) from exc

            choice = response.choices[0]
            finish = choice.finish_reason

            # Tool call path
            if finish == "tool_calls" and choice.message.tool_calls:
                messages.append(choice.message)  # assistant message with tool_calls
                for tc in choice.message.tool_calls:
                    fn_name = tc.function.name
                    tool_calls_made.append(fn_name)
                    tool_result = await self._execute_tool(fn_name, tc.function.arguments)
                    messages.append({
                        "role": "tool",
                        "tool_call_id": tc.id,
                        "content": str(tool_result),
                    })
                    logger.info("Tool %s executed → %d chars output", fn_name, len(str(tool_result)))
                continue

            content = (choice.message.content or "").strip()

            # Prompt-mode fallback: the model emits a JSON tool-call envelope as
            # text (used when the server does not return native tool_calls).
            if self.tool_mode != "native" and self.tools:
                call = _extract_tool_call(content)
                if call:
                    name, args = call
                    tool_calls_made.append(name)
                    tool_result = await self._execute_tool(name, json.dumps(args))
                    messages.append({"role": "assistant", "content": content})
                    messages.append({
                        "role": "user",
                        "content": (
                            f"[Result of {name}]\n{tool_result}\n\n"
                            f"Use this to continue, or give your final answer to the user."
                        ),
                    })
                    logger.info("Prompt-tool %s executed → %d chars output", name, len(str(tool_result)))
                    continue

            # Final answer
            return content, tool_calls_made, iteration + 1

        # Exhausted iterations — return whatever the last assistant message was
        last_assistant = next(
            (m.get("content", "") for m in reversed(messages) if m.get("role") == "assistant"),
            "I'm sorry, I couldn't complete the task within the allowed steps.",
        )
        return last_assistant, tool_calls_made, self.max_iterations

    async def _execute_tool(self, name: str, arguments_json: str) -> str:
        tool = self.tools.get(name)
        if not tool:
            return f"Error: tool '{name}' not found."
        try:
            args = json.loads(arguments_json) if arguments_json else {}
            result = await tool.run(**args)
            return str(result)
        except Exception as exc:
            logger.error("Tool %s raised: %s", name, exc)
            return f"Tool error: {exc}"

    def _tool_protocol_prompt(self) -> str:
        """System-prompt block describing the tools and the JSON call envelope
        (prompt mode only)."""
        if not self.tools:
            return ""
        lines = [
            "--- Available Tools ---",
            "You can call tools to gather information before answering.",
        ]
        for t in self.tools.values():
            props = (t.parameters_schema or {}).get("properties", {})
            params = ", ".join(f"{k}: {v.get('type', 'any')}" for k, v in props.items())
            lines.append(f"- {t.name}({params}) — {t.description}")
        lines += [
            "",
            "To call a tool, reply with ONLY this JSON object and nothing else:",
            '{"tool_call": {"name": "<tool_name>", "arguments": {<args>}}}',
            "You will then receive the tool's result and may call another tool or answer.",
            "When you have enough information, reply to the user normally, WITHOUT any JSON.",
            "Only use the tools listed above, with the exact argument names shown.",
        ]
        return "\n".join(lines)

    def _build_system(self, role_prompt: str, language: str) -> str:
        master = self.settings.get("master_prompt", _MASTER_PROMPT_FALLBACK).strip()
        parts = [master]
        if role_prompt:
            parts.append(f"\n--- User Role Context ---\n{role_prompt}")
        parts.append(f"\n--- Language ---\n{lang_instruction(language)}")
        parts.append(f"\n{_LANGUAGE_POLICY}")
        parts.append(f"\n{_WHATSAPP_FORMAT_RULES}")
        return "\n".join(parts)

    @staticmethod
    def _build_user_content(text: str, attachment_meta: dict | None) -> str:
        if not attachment_meta:
            return text or "(no message)"
        mime = attachment_meta.get("mime", "")
        name = attachment_meta.get("name", "file")
        path = attachment_meta.get("path", "")
        caption = attachment_meta.get("caption", "")
        file_desc = f"[Attached file: {name} | type: {mime} | path: {path}]"
        if caption:
            file_desc += f" | Caption: {caption}"
        return f"{text}\n{file_desc}".strip() if text else file_desc
